# Generated by Django 2.2.12 on 2020-09-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('seq', models.CharField(max_length=200, unique=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('seq', models.CharField(max_length=200, unique=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
