# Generated by Django 3.1.2 on 2020-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='seq',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='seqcore',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='smart',
            name='seq',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='smart',
            name='seqcore',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
