# Generated by Django 3.1.1 on 2020-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=200)),
                ('sample_id', models.IntegerField()),
                ('sample_number', models.IntegerField(default=0)),
                ('sample_name', models.CharField(max_length=200)),
                ('cell_number', models.IntegerField(default=0)),
                ('read_number', models.IntegerField(default=0)),
                ('smart_id', models.IntegerField()),
                ('alfa_subsample_id', models.IntegerField()),
                ('alfa_subsample_name', models.CharField(default='', max_length=200)),
                ('alfa_index_id', models.IntegerField()),
                ('alfa_index_number', models.IntegerField(default=0)),
                ('beta_subsample_id', models.IntegerField()),
                ('beta_subsample_name', models.CharField(default='', max_length=200)),
                ('beta_index_id', models.IntegerField()),
                ('beta_index_number', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
