# Generated by Django 2.2.12 on 2020-10-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='alfa_index_benchling',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='beta_index_benchling',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='smart_benchling',
            field=models.CharField(default='', max_length=200),
        ),
    ]
