# Generated by Django 3.1.2 on 2020-11-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20201027_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='ident',
            field=models.CharField(max_length=200),
        ),
    ]
