# Generated by Django 3.1.2 on 2020-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20201116_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='experiment_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
