# Generated by Django 3.1.2 on 2020-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='thread',
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
    ]
