# Generated by Django 3.1.2 on 2020-12-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_taskqueue_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskqueue',
            name='status',
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='output_file',
            field=models.CharField(default='', max_length=200),
        ),
    ]
